version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - "3010:3010"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        depends_on:
            - php
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
